1. KNN – 기반 모델링 분류
최적의 찾기 K

In [3]:
import pandas as pd
import numpy as np

In [2]:
file='./data/ab_data.csv'

In [4]:
df=pd.read_csv(file)

In [5]:
df

    Weight  Length Species
0      242    25.4       A
1      290    26.3       A
2      340    26.5       A
3      363    29.0       A
4      430    29.0       A
5      450    29.7       A
6      500    29.7       A
7      390    30.0       A
8      450    30.0       A
9      500    30.7       A
10     475    31.0       A
11     500    31.0       A
12     500    31.5       A
13     340    32.0       A
14     600    32.0       A
15     600    32.0       A
16     700    33.0       A
17     700    33.0       A
18     610    33.5       A
19     650    33.5       A
20     575    34.0       A
21     685    34.0       A
22     620    34.5       A
23     680    35.0       A
24     700    35.0       A
25     725    35.0       A
26     720    35.0       A
27     714    36.0       A
28     850    36.0       A
29    1000    37.0       A
30     920    38.5       A
31     955    38.5       A
32     925    39.5       A
33     975    41.0       A
34     950    41.0       A
35      40    14.1       B
36      69    18.2       B
37      78    18.8       B
38      87    19.8       B
39     120    20.0       B
40       0    20.5       B
41     110    20.8       B
42     120    21.0       B
43     150    22.0       B
44     145    22.0       B
45     160    22.5       B
46     140    22.5       B
47     160    22.5       B
48     169    24.0       B
49     161    23.4       B
50     200    23.5       B
51     180    25.2       B
52     290    26.0       B
53     272    27.0       B
54     390    31.7       B

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55 entries, 0 to 54
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Weight   55 non-null     int64
 1   Length   55 non-null     float64
 2   Species  55 non-null     object
dtypes: float64(1), int64(1), object(1)
memory usage: 1.4+ KB

In [7]:
df.isnull().sum()

Weight     0
Length     0
Species    0
dtype: int64

In [10]:
df['Weight'].unique()

array([ 242,  290,  340,  363,  430,  450,  500,  390,  475,  600,  700,
        610,  650,  575,  685,  620,  680,  725,  720,  714,  850, 1000,
        920,  955,  925,  975,  950,   40,   69,   78,   87,  120,    0,
        110,  150,  145,  160,  140,  169,  161,  200,  180,  272],
      dtype=int64)

In [11]:
df['Length'].unique()

array([25.4, 26.3, 26.5, 29. , 29.7, 30. , 30.7, 31. , 31.5, 32. , 33. ,
       33.5, 34. , 34.5, 35. , 36. , 37. , 38.5, 39.5, 41. , 14.1, 18.2,
       18.8, 19.8, 20. , 20.5, 20.8, 21. , 22. , 22.5, 24. , 23.4, 23.5,
       25.2, 26. , 27. , 31.7])

In [12]:
df['Species'].unique()

array(['A', 'B'], dtype=object)

In [19]:
data=pd.read_csv('./data/ab_data.csv', usecols = [0, 1])
target_df=df['Species']

In [20]:
data

    Weight  Length
0      242    25.4
1      290    26.3
2      340    26.5
3      363    29.0
4      430    29.0
5      450    29.7
6      500    29.7
7      390    30.0
8      450    30.0
9      500    30.7
10     475    31.0
11     500    31.0
12     500    31.5
13     340    32.0
14     600    32.0
15     600    32.0
16     700    33.0
17     700    33.0
18     610    33.5
19     650    33.5
20     575    34.0
21     685    34.0
22     620    34.5
23     680    35.0
24     700    35.0
25     725    35.0
26     720    35.0
27     714    36.0
28     850    36.0
29    1000    37.0
30     920    38.5
31     955    38.5
32     925    39.5
33     975    41.0
34     950    41.0
35      40    14.1
36      69    18.2
37      78    18.8
38      87    19.8
39     120    20.0
40       0    20.5
41     110    20.8
42     120    21.0
43     150    22.0
44     145    22.0
45     160    22.5
46     140    22.5
47     160    22.5
48     169    24.0
49     161    23.4
50     200    23.5
51     180    25.2
52     290    26.0
53     272    27.0
54     390    31.7

In [21]:
import numpy as np
data = np.array(data)
target_df = np.array(target_df)

In [22]:
from sklearn.neighbors import KNeighborsClassifier
kn = KNeighborsClassifier()

In [23]:
from sklearn.model_selection import train_test_split

In [24]:
train_input, test_input, train_target, test_target = train_test_split(
    data, target_df, stratify = target_df, test_size = 0.2)

In [25]:
kn.fit(train_input, train_target)

KNeighborsClassifier()

In [26]:
kn.score(test_input, test_target)

1.0

In [27]:
for k in range(1, 56):
    kn.n_neighbors = k
    kn.fit(data, target_df)
    print(f'[{k}]: {kn.score(data, target_df)}')

[1]: 1.0
[2]: 0.9454545454545454
[3]: 0.9454545454545454
[4]: 0.9272727272727272
[5]: 0.9272727272727272
[6]: 0.9272727272727272
[7]: 0.9272727272727272
[8]: 0.9272727272727272
[9]: 0.9272727272727272
[10]: 0.9272727272727272
[11]: 0.9454545454545454
[12]: 0.9454545454545454
[13]: 0.9454545454545454
[14]: 0.9454545454545454
[15]: 0.9454545454545454
[16]: 0.9454545454545454
[17]: 0.9454545454545454
[18]: 0.9454545454545454
[19]: 0.9454545454545454
[20]: 0.9454545454545454
[21]: 0.9454545454545454
[22]: 0.9454545454545454
[23]: 0.9454545454545454
[24]: 0.9454545454545454
[25]: 0.9454545454545454
[26]: 0.9454545454545454
[27]: 0.9454545454545454
[28]: 0.9454545454545454
[29]: 0.9090909090909091
[30]: 0.9454545454545454
[31]: 0.9090909090909091
[32]: 0.9454545454545454
[33]: 0.9454545454545454
[34]: 0.9454545454545454
[35]: 0.9454545454545454
[36]: 0.9454545454545454
[37]: 0.9454545454545454
[38]: 0.9454545454545454
[39]: 0.9454545454545454
[40]: 0.6363636363636364
[41]: 0.6363636363636364
[42]: 0.6363636363636364
[43]: 0.6363636363636364
[44]: 0.6363636363636364
[45]: 0.6363636363636364
[46]: 0.6363636363636364
[47]: 0.6363636363636364
[48]: 0.6363636363636364
[49]: 0.6363636363636364
[50]: 0.6363636363636364
[51]: 0.6363636363636364
[52]: 0.6363636363636364
[53]: 0.6363636363636364
[54]: 0.6363636363636364
[55]: 0.6363636363636364