In [151]:
import pandas as pd 
fragrance_df=pd.read_csv('./MyData/fragrance.csv')

In [152]:
fragrance_df.head(3)

,브랜드,이름,성별,TPO,계절감,향의농도,특성,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22
0,1,롬브로단로EDP,중성,"캐쥬얼,포멀",사계절,무거운,"플로럴,그린,우디,얼씨,프루티",NaN,NaN,NaN,...,NaN,특성1,특성2,특성3,특성4,특성5,특성6,특성7,NaN,NaN
1,1,필로시코스EDP,여성,캐쥬얼,"봄,여름",가벼운,"그린,프레쉬,우디,얼씨,프루티",NaN,NaN,NaN,...,NaN,플로럴,그린,우디,얼씨,프루티,프레쉬,시트러스,NaN,26개의 열을 만들어서 나머지는0 해당하는것에는 1
2,1,베티베리오EDP,중성,"캐쥬얼,포멀","가을,겨울",무거운,"우디,시트러스,얼씨,그린,플로럴",NaN,NaN,NaN,...,NaN,꽃향기,풀내음,나무내음,신선한 흙내음,과일향,"신선한 향, 깨끗한 향",상큼한향,NaN,NaN

In [153]:
perfume = fragrance_df.iloc[:173,:7]

In [154]:
perfume.head()

   브랜드        이름  성별     TPO      계절감 향의농도                   특성
0    1  롬브로단로EDP  중성  캐쥬얼,포멀      사계절  무거운     플로럴,그린,우디,얼씨,프루티
1    1  필로시코스EDP  여성     캐쥬얼     봄,여름  가벼운     그린,프레쉬,우디,얼씨,프루티
2    1  베티베리오EDP  중성  캐쥬얼,포멀    가을,겨울  무거운    우디,시트러스,얼씨,그린,플로럴
3    1     도손EDP  중성  캐쥬얼,포멀  봄,가을,겨울  무거운  프레쉬,파우더리,머스크,그린,플로럴
4    1     도손EDT  여성     캐쥬얼      사계절   중간  프레쉬,파우더리,머스크,그린,플로럴

In [155]:
l = '플로럴 그린 우디 얼씨 프루티 프레쉬 시트러스 머스크 파우더리 민트 부지 마린 코코넛 스파이시 앰버 레더 아로마틱 로즈 스모키 타바코 바닐라 라벤더 워터리 너티 메탈릭 프랄린'.split()
for i in l:
    perfume[i] = 0

In [156]:
for i in range(len(perfume)):
    j = perfume.iloc[i,6].split(',')
    for k in j:
        perfume.loc[i,k] = 1

In [157]:
perfume.head()

,브랜드,이름,성별,TPO,계절감,향의농도,특성,플로럴,그린,우디,...,아로마틱,로즈,스모키,타바코,바닐라,라벤더,워터리,너티,메탈릭,프랄린
0,1,롬브로단로EDP,중성,"캐쥬얼,포멀",사계절,무거운,"플로럴,그린,우디,얼씨,프루티",1,1,1,...,0,0,0,0,0,0,0,0,0,0
1,1,필로시코스EDP,여성,캐쥬얼,"봄,여름",가벼운,"그린,프레쉬,우디,얼씨,프루티",0,1,1,...,0,0,0,0,0,0,0,0,0,0
2,1,베티베리오EDP,중성,"캐쥬얼,포멀","가을,겨울",무거운,"우디,시트러스,얼씨,그린,플로럴",1,1,1,...,0,0,0,0,0,0,0,0,0,0
3,1,도손EDP,중성,"캐쥬얼,포멀","봄,가을,겨울",무거운,"프레쉬,파우더리,머스크,그린,플로럴",1,1,0,...,0,0,0,0,0,0,0,0,0,0
4,1,도손EDT,여성,캐쥬얼,사계절,중간,"프레쉬,파우더리,머스크,그린,플로럴",1,1,0,...,0,0,0,0,0,0,0,0,0,0

In [158]:
len(perfume.columns)
# 향수 몰라
# 브랜드 추천 -> 향수 추천

33

In [159]:
perfume.iloc[:,7:32]

,플로럴,그린,우디,얼씨,프루티,프레쉬,시트러스,머스크,파우더리,민트,...,레더,아로마틱,로즈,스모키,타바코,바닐라,라벤더,워터리,너티,메탈릭
0,1,1,1,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,1,1,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,1,1,1,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1,1,0,0,0,1,0,1,1,0,...,0,0,0,0,0,0,0,0,0,0
4,1,1,0,0,0,1,0,1,1,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
168,0,0,1,0,1,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
169,0,0,1,0,1,0,0,0,1,0,...,0,1,0,0,0,0,0,0,0,0
170,1,0,1,0,1,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
171,1,0,1,0,0,0,0,0,1,0,...,0,0,0,0,0,1,0,0,0,0
172,0,0,1,0,0,0,0,1,1,0,...,0,0,0,0,0,0,0,0,0,0

In [160]:
perfume.iloc[:,1]

0         롬브로단로EDP
1         필로시코스EDP
2         베티베리오EDP
3            도손EDP
4            도손EDT
          ...
168       우드자스민EDP
169       그리사르넬EDP
170        빠스수아EDP
171    튜베로즈임페리얼EDP
172        셀다르장EDP
Name: 이름, Length: 173, dtype: object

In [161]:
# 'col1' 열을 숫자로 바꾸기
perfume.iloc[:,1] = pd.factorize(perfume.iloc[:,1])[0] + 1

print(perfume.iloc[:,1])

0        1
1        2
2        3
3        4
4        5
      ...
168    169
169    170
170    171
171    172
172    173
Name: 이름, Length: 173, dtype: int64

C:\Users\y2kjd\AppData\Local\Temp\ipykernel_22788\3651513133.py:2: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  perfume.iloc[:,1] = pd.factorize(perfume.iloc[:,1])[0] + 1

In [162]:
perfume

,브랜드,이름,성별,TPO,계절감,향의농도,특성,플로럴,그린,우디,...,아로마틱,로즈,스모키,타바코,바닐라,라벤더,워터리,너티,메탈릭,프랄린
0,1,1,중성,"캐쥬얼,포멀",사계절,무거운,"플로럴,그린,우디,얼씨,프루티",1,1,1,...,0,0,0,0,0,0,0,0,0,0
1,1,2,여성,캐쥬얼,"봄,여름",가벼운,"그린,프레쉬,우디,얼씨,프루티",0,1,1,...,0,0,0,0,0,0,0,0,0,0
2,1,3,중성,"캐쥬얼,포멀","가을,겨울",무거운,"우디,시트러스,얼씨,그린,플로럴",1,1,1,...,0,0,0,0,0,0,0,0,0,0
3,1,4,중성,"캐쥬얼,포멀","봄,가을,겨울",무거운,"프레쉬,파우더리,머스크,그린,플로럴",1,1,0,...,0,0,0,0,0,0,0,0,0,0
4,1,5,여성,캐쥬얼,사계절,중간,"프레쉬,파우더리,머스크,그린,플로럴",1,1,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
168,50,169,중성,포멀,"가을,겨울",무거운,"앰버,프루티,우디,스모키,프루티",0,0,1,...,0,0,1,0,0,0,0,0,0,0
169,50,170,중성,"캐쥬얼,포멀","봄,가을,겨울",중간,"우디,스파이시,아로마틱,파우더리,프루티",0,0,1,...,1,0,0,0,0,0,0,0,0,0
170,50,171,중성,"캐쥬얼,포멀",사계절,중간,"플로럴,우디,프루티,시트러스,앰버",1,0,1,...,0,0,0,0,0,0,0,0,0,0
171,50,172,여성,포멀,"봄,가을,겨울",무거운,"플로럴,우디,바닐라,파우더리,앰버",1,0,1,...,0,0,0,0,1,0,0,0,0,0
172,50,173,중성,캐쥬얼,"봄,여름",가벼운,"머스크,앰버,우디,마린,파우더리",0,0,1,...,0,0,0,0,0,0,0,0,0,0

In [163]:
# 문자열을 숫자로 바꾸기 위한 매핑 딕셔너리 생성
mapping = {'남성': 1, '여성': 2, '중성': 3}

# 'col1' 열의 값을 매핑 딕셔너리를 사용하여 숫자로 변환
perfume['성별'] = perfume['성별'].map(mapping)



# 문자열을 숫자로 바꾸기 위한 매핑 딕셔너리 생성
mapping = {'캐쥬얼': 1, '포멀': 2, '캐쥬얼,포멀': 3}

# 'col1' 열의 값을 매핑 딕셔너리를 사용하여 숫자로 변환
perfume['TPO'] = perfume['TPO'].map(mapping)

print(perfume)

     브랜드   이름  성별  TPO      계절감 향의농도                     특성  플로럴  그린  우디  ...  \
0      1    1   3    3      사계절  무거운       플로럴,그린,우디,얼씨,프루티    1   1   1  ...
1      1    2   2    1     봄,여름  가벼운       그린,프레쉬,우디,얼씨,프루티    0   1   1  ...
2      1    3   3    3    가을,겨울  무거운      우디,시트러스,얼씨,그린,플로럴    1   1   1  ...
3      1    4   3    3  봄,가을,겨울  무거운    프레쉬,파우더리,머스크,그린,플로럴    1   1   0  ...
4      1    5   2    1      사계절   중간    프레쉬,파우더리,머스크,그린,플로럴    1   1   0  ...
..   ...  ...  ..  ...      ...  ...                    ...  ...  ..  ..  ...
168   50  169   3    2    가을,겨울  무거운      앰버,프루티,우디,스모키,프루티    0   0   1  ...
169   50  170   3    3  봄,가을,겨울   중간  우디,스파이시,아로마틱,파우더리,프루티    0   0   1  ...
170   50  171   3    3      사계절   중간     플로럴,우디,프루티,시트러스,앰버    1   0   1  ...
171   50  172   2    2  봄,가을,겨울  무거운     플로럴,우디,바닐라,파우더리,앰버    1   0   1  ...
172   50  173   3    1     봄,여름  가벼운      머스크,앰버,우디,마린,파우더리    0   0   1  ...

     아로마틱  로즈  스모키  타바코  바닐라  라벤더  워터리  너티  메탈릭  프랄린
0       0   0    0    0    0    0    0   0    0    0
1       0   0    0    0    0    0    0   0    0    0
2       0   0    0    0    0    0    0   0    0    0
3       0   0    0    0    0    0    0   0    0    0
4       0   0    0    0    0    0    0   0    0    0
..    ...  ..  ...  ...  ...  ...  ...  ..  ...  ...
168     0   0    1    0    0    0    0   0    0    0
169     1   0    0    0    0    0    0   0    0    0
170     0   0    0    0    0    0    0   0    0    0
171     0   0    0    0    1    0    0   0    0    0
172     0   0    0    0    0    0    0   0    0    0

[173 rows x 33 columns]

In [164]:
# '특성' 열 삭제
perfume = perfume.drop('특성', axis=1)

In [165]:
perfume

,브랜드,이름,성별,TPO,계절감,향의농도,플로럴,그린,우디,얼씨,...,아로마틱,로즈,스모키,타바코,바닐라,라벤더,워터리,너티,메탈릭,프랄린
0,1,1,3,3,사계절,무거운,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
1,1,2,2,1,"봄,여름",가벼운,0,1,1,1,...,0,0,0,0,0,0,0,0,0,0
2,1,3,3,3,"가을,겨울",무거운,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
3,1,4,3,3,"봄,가을,겨울",무거운,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1,5,2,1,사계절,중간,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
168,50,169,3,2,"가을,겨울",무거운,0,0,1,0,...,0,0,1,0,0,0,0,0,0,0
169,50,170,3,3,"봄,가을,겨울",중간,0,0,1,0,...,1,0,0,0,0,0,0,0,0,0
170,50,171,3,3,사계절,중간,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
171,50,172,2,2,"봄,가을,겨울",무거운,1,0,1,0,...,0,0,0,0,1,0,0,0,0,0
172,50,173,3,1,"봄,여름",가벼운,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0

In [166]:
perfume

,브랜드,이름,성별,TPO,계절감,향의농도,플로럴,그린,우디,얼씨,...,아로마틱,로즈,스모키,타바코,바닐라,라벤더,워터리,너티,메탈릭,프랄린
0,1,1,3,3,사계절,무거운,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
1,1,2,2,1,"봄,여름",가벼운,0,1,1,1,...,0,0,0,0,0,0,0,0,0,0
2,1,3,3,3,"가을,겨울",무거운,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
3,1,4,3,3,"봄,가을,겨울",무거운,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1,5,2,1,사계절,중간,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
168,50,169,3,2,"가을,겨울",무거운,0,0,1,0,...,0,0,1,0,0,0,0,0,0,0
169,50,170,3,3,"봄,가을,겨울",중간,0,0,1,0,...,1,0,0,0,0,0,0,0,0,0
170,50,171,3,3,사계절,중간,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
171,50,172,2,2,"봄,가을,겨울",무거운,1,0,1,0,...,0,0,0,0,1,0,0,0,0,0
172,50,173,3,1,"봄,여름",가벼운,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0

In [167]:
# 문자열을 숫자로 바꾸기 위한 매핑 딕셔너리 생성
mapping = {'가벼운': 1, '무거운': 2, '중간': 3}

# 'col1' 열의 값을 매핑 딕셔너리를 사용하여 숫자로 변환
perfume['향의농도'] = perfume['향의농도'].map(mapping)

In [168]:
perfume

,브랜드,이름,성별,TPO,계절감,향의농도,플로럴,그린,우디,얼씨,...,아로마틱,로즈,스모키,타바코,바닐라,라벤더,워터리,너티,메탈릭,프랄린
0,1,1,3,3,사계절,2,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
1,1,2,2,1,"봄,여름",1,0,1,1,1,...,0,0,0,0,0,0,0,0,0,0
2,1,3,3,3,"가을,겨울",2,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
3,1,4,3,3,"봄,가을,겨울",2,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1,5,2,1,사계절,3,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
168,50,169,3,2,"가을,겨울",2,0,0,1,0,...,0,0,1,0,0,0,0,0,0,0
169,50,170,3,3,"봄,가을,겨울",3,0,0,1,0,...,1,0,0,0,0,0,0,0,0,0
170,50,171,3,3,사계절,3,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
171,50,172,2,2,"봄,가을,겨울",2,1,0,1,0,...,0,0,0,0,1,0,0,0,0,0
172,50,173,3,1,"봄,여름",1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0

In [169]:
perfume['계절감'].value_counts()

가을,겨울       63
봄,여름        38
봄,가을,겨울     30
사계절         20
봄,여름,가을     17
여름,가을,겨울     3
봄,가을         2
Name: 계절감, dtype: int64

In [170]:
perfume

,브랜드,이름,성별,TPO,계절감,향의농도,플로럴,그린,우디,얼씨,...,아로마틱,로즈,스모키,타바코,바닐라,라벤더,워터리,너티,메탈릭,프랄린
0,1,1,3,3,사계절,2,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
1,1,2,2,1,"봄,여름",1,0,1,1,1,...,0,0,0,0,0,0,0,0,0,0
2,1,3,3,3,"가을,겨울",2,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
3,1,4,3,3,"봄,가을,겨울",2,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1,5,2,1,사계절,3,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
168,50,169,3,2,"가을,겨울",2,0,0,1,0,...,0,0,1,0,0,0,0,0,0,0
169,50,170,3,3,"봄,가을,겨울",3,0,0,1,0,...,1,0,0,0,0,0,0,0,0,0
170,50,171,3,3,사계절,3,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
171,50,172,2,2,"봄,가을,겨울",2,1,0,1,0,...,0,0,0,0,1,0,0,0,0,0
172,50,173,3,1,"봄,여름",1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0

In [171]:
# 문자열을 숫자로 바꾸기 위한 매핑 딕셔너리 생성
mapping = {'봄,여름': 1, '봄,가을': 2, '봄,여름,가을': 3, '봄,가을,겨울':4, '여름,가을,겨울':5, '가을,겨울':6, '사계절':7}

# 'col1' 열의 값을 매핑 딕셔너리를 사용하여 숫자로 변환
perfume['계절감'] = perfume['계절감'].map(mapping)

In [192]:
perfume.columns

Index(['브랜드', '이름', '성별', 'TPO', '계절감', '향의농도', '플로럴', '그린', '우디', '얼씨', '프루티',
       '프레쉬', '시트러스', '머스크', '파우더리', '민트', '부지', '마린', '코코넛', '스파이시', '앰버',
       '레더', '아로마틱', '로즈', '스모키', '타바코', '바닐라', '라벤더', '워터리', '너티', '메탈릭',
       '프랄린'],
      dtype='object')

In [173]:
import pycaret

In [180]:
from pycaret.classification import *

In [181]:
exp=setup(data = perfume, target="이름")

In [182]:
a=compare_models()

In [184]:
from sklearn.ensemble import RandomForestClassifier

In [186]:
rf = RandomForestClassifier()

In [187]:
rf.fit(perfume.drop('이름',axis=1),perfume['이름'])

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [191]:
rf.predict([[1]*31])

array([2], dtype=int64)

### 향수 기호

In [202]:
# #브랜드	이름


# 딥디크	1
# 조말론	2
# 바이레도	3
# 이솝	4
# 톰포드	5
# 프레데릭말	6
# 퍼퓸드말리	7
# 조보이	8
# 제로보암	9
# 오케스트라퍼퓸	10
# 이니시오	11
# 메모	12
# 알마프	13
# 아프난	14
# 크리드	15
# 나소마토	16
# 산타마리아노벨라	17
# 디올	18
# 샤넬	19
# 자라	20
# 에따리브르도랑쥬	21
# 모스키노	22
# 아이젠버그	23
# 메종마르지엘라	24
# 밀러해리스	25
# 아쿠아디파르마	26
# 쇼파드	27
# 르라보	28
# 티지아나테렌지	29
# 메종프란시스커정	30
# 메종크리벨리	31
# 킬리안	32
# 라리크	33
# 펜할리곤스	34
# 에르메스	35
# 반클리프앤아펠	36
# 히스토리드퍼퓸	37
# 프레드릭엠	38
# 4160튜즈데이	39
# 꼼데가르송	40
# 버버리	41
# 파코라반	42
# 돌체앤가바나	43
# 제르조프	44
# 랑방	45
# 패리스힐튼	46
# 입생로랑	47
# 지미추	48
# mdci	49
# bdk	50



# 성별
# '남성': 1, '여성': 2, '중성': 3



# TPO
# '캐쥬얼': 1, '포멀': 2, '캐쥬얼,포멀': 3



# 계절감
# '봄,여름': 1, '봄,가을': 2, '봄,여름,가을': 3, '봄,가을,겨울':4, '여름,가을,겨울':5, '가을,겨울':6, '사계절':7



# 향의농도
# '가벼운': 1, '무거운': 2, '중간': 3

### 향수 특성(중요)

In [200]:
# '플로럴', '그린', '우디', '얼씨', '프루티','프레쉬', 
# '시트러스', '머스크', '파우더리', '민트', '부지', '마린', 
# '코코넛', '스파이시', '앰버','레더', '아로마틱', '로즈', '스모키', 
# '타바코', '바닐라', '라벤더', '워터리', '너티', '메탈릭','프랄린'

('타바코', '바닐라', '라벤더', '워터리', '너티', '메탈릭', '프랄린')

In [199]:
#rf.predict([[6,1,2,6,2,[3,4,11,18,20]]])
#0,0,1,1,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0
rf.predict([[6,1,2,6,2,0,0,1,1,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0]])

array([61], dtype=int64)

In [213]:
perfume.head(61)

,브랜드,이름,성별,TPO,계절감,향의농도,플로럴,그린,우디,얼씨,...,아로마틱,로즈,스모키,타바코,바닐라,라벤더,워터리,너티,메탈릭,프랄린
0,1,1,3,3,7,2,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
1,1,2,2,1,1,1,0,1,1,1,...,0,0,0,0,0,0,0,0,0,0
2,1,3,3,3,6,2,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
3,1,4,3,3,4,2,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1,5,2,1,7,3,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56,9,57,1,3,3,2,0,0,1,0,...,0,1,0,0,0,0,0,0,0,0
57,9,58,3,1,2,3,0,1,1,0,...,0,0,0,0,0,0,0,0,0,0
58,9,59,3,3,3,2,0,1,1,0,...,0,0,0,0,0,0,0,0,0,0
59,10,60,1,2,6,2,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
60,11,61,2,2,6,2,0,0,1,0,...,0,0,0,1,1,0,0,0,0,0

In [208]:
rf.predict_proba([[6,1,2,6,2,0,0,1,1,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0]])

array([[0.  , 0.  , 0.01, 0.  , 0.  , 0.  , 0.01, 0.  , 0.  , 0.  , 0.  ,
        0.  , 0.  , 0.  , 0.01, 0.  , 0.  , 0.  , 0.  , 0.02, 0.08, 0.01,
        0.  , 0.01, 0.  , 0.  , 0.  , 0.02, 0.  , 0.  , 0.03, 0.02, 0.01,
        0.03, 0.01, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.03, 0.  ,
        0.  , 0.01, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.05, 0.  , 0.  ,
        0.  , 0.02, 0.  , 0.  , 0.  , 0.17, 0.  , 0.  , 0.  , 0.  , 0.  ,
        0.  , 0.02, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
        0.  , 0.  , 0.06, 0.02, 0.01, 0.  , 0.03, 0.  , 0.  , 0.  , 0.  ,
        0.  , 0.01, 0.  , 0.01, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.01,
        0.  , 0.  , 0.  , 0.  , 0.  , 0.06, 0.  , 0.  , 0.  , 0.01, 0.  ,
        0.  , 0.  , 0.  , 0.  , 0.01, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
        0.  , 0.  , 0.08, 0.01, 0.  , 0.  , 0.01, 0.01, 0.  , 0.01, 0.  ,
        0.  , 0.  , 0.01, 0.  , 0.  , 0.02, 0.  , 0.01, 0.  , 0.  , 0.  ,
        0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
        0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
        0.03, 0.  , 0.  , 0.01, 0.  , 0.  , 0.  , 0.  ]])

In [204]:
#플로럴, 그린, 우디,시트러스,워터리
rf.predict([[44,3,1,1,3,1,1,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0]])

array([155], dtype=int64)

In [206]:
#바닐라, 타바코, 라벤더, 시트러스, 스파이시
rf.predict([[44,3,3,3,2,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,1,1,1,1,0,0,0,0]])

array([153], dtype=int64)

In [207]:
rf.predict_proba([[44,3,3,3,2,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,1,1,1,1,0,0,0,0]])

array([[0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
        0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.01,
        0.  , 0.  , 0.  , 0.  , 0.03, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
        0.  , 0.  , 0.  , 0.  , 0.  , 0.01, 0.  , 0.  , 0.  , 0.  , 0.  ,
        0.01, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
        0.  , 0.01, 0.  , 0.01, 0.  , 0.01, 0.  , 0.  , 0.  , 0.  , 0.  ,
        0.  , 0.02, 0.  , 0.  , 0.  , 0.01, 0.  , 0.  , 0.01, 0.  , 0.  ,
        0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.03, 0.  , 0.  , 0.  ,
        0.01, 0.02, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
        0.  , 0.  , 0.  , 0.  , 0.  , 0.01, 0.01, 0.  , 0.  , 0.  , 0.  ,
        0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.01, 0.  , 0.  ,
        0.01, 0.04, 0.  , 0.03, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
        0.  , 0.  , 0.  , 0.01, 0.  , 0.  , 0.  , 0.  , 0.  , 0.06, 0.  ,
        0.  , 0.01, 0.  , 0.02, 0.  , 0.  , 0.  , 0.  , 0.  , 0.55, 0.  ,
        0.  , 0.01, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
        0.01, 0.  , 0.  , 0.02, 0.01, 0.  , 0.  , 0.  ]])

In [209]:
# 휠 4,3,3,6,2,[2,3,4,14,15]

rf.predict([[4,3,3,6,2,0,1,1,1,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0]])

array([15], dtype=int64)

In [210]:
perfume

,브랜드,이름,성별,TPO,계절감,향의농도,플로럴,그린,우디,얼씨,...,아로마틱,로즈,스모키,타바코,바닐라,라벤더,워터리,너티,메탈릭,프랄린
0,1,1,3,3,7,2,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
1,1,2,2,1,1,1,0,1,1,1,...,0,0,0,0,0,0,0,0,0,0
2,1,3,3,3,6,2,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
3,1,4,3,3,4,2,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1,5,2,1,7,3,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
168,50,169,3,2,6,2,0,0,1,0,...,0,0,1,0,0,0,0,0,0,0
169,50,170,3,3,4,3,0,0,1,0,...,1,0,0,0,0,0,0,0,0,0
170,50,171,3,3,7,3,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
171,50,172,2,2,4,2,1,0,1,0,...,0,0,0,0,1,0,0,0,0,0
172,50,173,3,1,1,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0

In [211]:
# 배열이 포함된 열 선택
target_column = perfume['브랜드']

# 해당 배열의 인덱스 번호 추출
index = target_column[target_column==15].index[0]

# 해당 배열의 값을 출력
print(target_column[index])

15

In [212]:
perfume.head(15)

,브랜드,이름,성별,TPO,계절감,향의농도,플로럴,그린,우디,얼씨,...,아로마틱,로즈,스모키,타바코,바닐라,라벤더,워터리,너티,메탈릭,프랄린
0,1,1,3,3,7,2,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
1,1,2,2,1,1,1,0,1,1,1,...,0,0,0,0,0,0,0,0,0,0
2,1,3,3,3,6,2,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
3,1,4,3,3,4,2,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1,5,2,1,7,3,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
5,1,6,1,3,6,2,0,1,1,0,...,0,0,0,0,0,0,0,0,0,0
6,1,7,3,3,6,2,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
7,2,8,2,1,1,1,0,1,1,1,...,0,0,0,0,0,0,0,0,0,0
8,2,9,3,2,6,2,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
9,2,10,3,1,1,1,0,0,0,0,...,1,0,0,0,0,0,1,0,0,0
10,2,11,2,1,1,1,1,0,0,0,...,0,1,0,0,0,0,0,0,0,0
11,3,12,3,1,3,3,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
12,3,13,3,2,4,2,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
13,3,14,3,1,3,2,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
14,4,15,3,3,6,2,0,1,1,1,...,0,0,0,0,0,0,0,0,0,0

In [214]:
# 호림씨
# 32,1,1,4,3,[3,4,6,10,12]
rf.predict([[32,1,1,4,3,0,0,1,1,0,1,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0]])

array([108], dtype=int64)

In [215]:
perfume.head(108)

,브랜드,이름,성별,TPO,계절감,향의농도,플로럴,그린,우디,얼씨,...,아로마틱,로즈,스모키,타바코,바닐라,라벤더,워터리,너티,메탈릭,프랄린
0,1,1,3,3,7,2,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
1,1,2,2,1,1,1,0,1,1,1,...,0,0,0,0,0,0,0,0,0,0
2,1,3,3,3,6,2,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
3,1,4,3,3,4,2,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1,5,2,1,7,3,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103,24,104,3,3,6,2,0,0,1,0,...,0,0,0,0,1,0,0,1,0,0
104,24,105,1,2,6,2,0,0,1,0,...,0,0,1,0,1,0,0,0,0,0
105,24,106,3,2,4,2,0,1,1,0,...,0,0,0,0,0,0,0,0,0,0
106,24,107,3,1,6,3,0,1,1,0,...,0,0,0,0,1,0,0,0,0,0
107,25,108,3,1,1,1,0,1,1,0,...,1,0,0,0,0,0,0,0,0,0

In [218]:
# 르 동우 무슈
# 24,3,1,7,1,[1,6,7,8,9]
rf.predict([[24,3,1,7,1,1,0,0,0,0,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]])

array([145], dtype=int64)

In [219]:
# 르 오야붕 무슈
# 18,3,1,1,2,[5,6,7,10,12]
rf.predict([[18,3,1,1,2,0,0,0,0,1,1,1,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0]])

array([100], dtype=int64)

In [220]:
# 지은센세
# 1,3,3,1,1,[1,2,5,6,7]
rf.predict([[1,3,3,1,1,1,1,0,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,]])

array([112], dtype=int64)

In [221]:
# 마가님
# 2,1,1,6,1,[3,4,5,8,15]
rf.predict([[2,1,1,6,1,0,0,1,1,1,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0]])

array([34], dtype=int64)

In [222]:
rf.predict_proba([[2,1,1,6,1,0,0,1,1,1,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0]])

array([[0.05, 0.06, 0.  , 0.  , 0.01, 0.02, 0.  , 0.01, 0.01, 0.  , 0.  ,
        0.  , 0.01, 0.04, 0.01, 0.  , 0.01, 0.01, 0.01, 0.  , 0.01, 0.  ,
        0.01, 0.  , 0.  , 0.  , 0.  , 0.01, 0.  , 0.  , 0.  , 0.01, 0.  ,
        0.34, 0.02, 0.01, 0.  , 0.01, 0.01, 0.  , 0.04, 0.  , 0.  , 0.  ,
        0.  , 0.  , 0.  , 0.01, 0.  , 0.  , 0.01, 0.  , 0.07, 0.  , 0.02,
        0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
        0.02, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
        0.  , 0.  , 0.  , 0.01, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
        0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.01, 0.01, 0.  ,
        0.  , 0.01, 0.  , 0.  , 0.  , 0.  , 0.01, 0.  , 0.  , 0.01, 0.  ,
        0.  , 0.  , 0.  , 0.  , 0.01, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
        0.02, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
        0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.02, 0.  , 0.02,
        0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
        0.  , 0.  , 0.  , 0.01, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
        0.  , 0.  , 0.  , 0.01, 0.  , 0.  , 0.  , 0.  ]])